import { Col, Container, Row } from "react-bootstrap";
import SideNav from "./_components/SideNav/SideNav";
import TopHeader from "./_components/TopHeader/TopHeader";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`text-bg-dark h-100  p-0 g-0`}>
        <Container>
          <TopHeader />
          <Row className={`justify-content-between px-0`}>
            <Col sm={2} className={` d-none d-lg-block px-0`}>
              <SideNav />
            </Col>
            <Col
              sm={12}
              lg={10}
              className={`flex-grow-1 d-flex justify-content-center align-items-center`}
            >
              {children}
            </Col>
          </Row>
        </Container>
      </body>
    </html>
  );
}
